1. Reloading input feature engineering and applying it on new input data
2. Reloading model and predicting output based on the model trained on new input

In [5]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [3]:
loaded_model = load_model('churn_model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [4]:
with open('scaler.pkl', 'rb') as f:   #read byte - rb, write byte - wb
    scaler = pickle.load(f)

with open('gender_encoder.pkl', 'rb') as f:
    gender_encoder = pickle.load(f)

with open('geography_encoder.pkl', 'rb') as f:
    geography_encoder = pickle.load(f)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:525: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:525: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:525: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.6.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [14]:
input_data = pd.DataFrame([{'CreditScore':600,
                           'Geography':'France',
                           'Gender':'Male',
                           'Age':40,
                           'Tenure':5,
                           'Balance':60000,
                           'NumOfProducts':2,
                           'HasCrCard':1,
                           'IsActiveMember':1,
                           'EstimatedSalary':50000,
}])

input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,5,60000,2,1,1,50000

In [15]:
input_data['Gender'] = gender_encoder.transform(input_data['Gender'])
geography_new = pd.DataFrame(geography_encoder.transform(input_data[['Geography']]),columns=geography_encoder.get_feature_names_out(['Geography']))

In [16]:
input_data = pd.concat([input_data.drop('Geography', axis=1),geography_new],axis=1)
input_data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,5,60000,2,1,1,50000,1.0,0.0,0.0

In [17]:
X = scaler.transform(input_data)

In [18]:
# prediction
prediction = loaded_model.predict(X)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[[0.03629248]]

In [22]:
# prediction probability
prediction[0][0]

np.float32(0.036292482)